{
 "title": "LoRaware /all",
 "time": { "from": "2019-10-16T06:06:13.953Z", "to": "2019-10-16T06:31:24.657Z" },
 "panels": [
  {
   "title": "Heart Rate",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "LoRaware 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_1",
     "query": "SELECT LAST(\"HR\") FROM \"LoRaware_1\"",
     "select": [
      [
       { "params": [ "HR" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_2",
     "query": "SELECT LAST(\"HR\") FROM \"LoRaware_2\"",
     "select": [
      [
       { "params": [ "HR" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_3",
     "query": "SELECT LAST(\"HR\") FROM \"LoRaware_3\"",
     "select": [
      [
       { "params": [ "HR" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_4",
     "query": "SELECT LAST(\"HR\") FROM \"LoRaware_4\"",
     "select": [
      [
       { "params": [ "HR" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blood Oximetery",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "alias": "LoRaware 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_1",
     "query": "SELECT LAST(\"O2\") FROM \"LoRaware_1\"",
     "select": [
      [
       { "params": [ "O2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_2",
     "query": "SELECT LAST(\"O2\") FROM \"LoRaware_2\" ",
     "select": [
      [
       { "params": [ "O2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_3",
     "query": "SELECT LAST(\"O2\") FROM \"LoRaware_3\"",
     "select": [
      [
       { "params": [ "O2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_4",
     "query": "SELECT LAST(\"O2\") FROM \"LoRaware_4\" ",
     "select": [
      [
       { "params": [ "O2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "alias": "LoRaware 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_1",
     "query": "SELECT last(\"Temp\") FROM \"LoRaware_1\" ",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_2",
     "query": "SELECT last(\"Temp\") FROM \"LoRaware_2\"",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_3",
     "query": "SELECT last(\"Temp\") FROM \"LoRaware_3\" ",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_4",
     "query": "SELECT last(\"Temp\") FROM \"LoRaware_4\" ",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "alias": "LoRaware 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_1",
     "query": "SELECT last(\"Hum\") FROM \"LoRaware_1\" ",
     "select": [
      [
       { "params": [ "Hum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_2",
     "query": "SELECT last(\"Hum\") FROM \"LoRaware_2\" ",
     "select": [
      [
       { "params": [ "Hum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_3",
     "query": "SELECT last(\"Hum\") FROM \"LoRaware_3\"",
     "select": [
      [
       { "params": [ "Hum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_4",
     "query": "SELECT last(\"Hum\") FROM \"LoRaware_4\" ",
     "select": [
      [
       { "params": [ "Hum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Battery Voltage",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 2, "y": 7 },
   "targets": [
    {
     "alias": "LoRaware 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_1",
     "query": "SELECT LAST(\"BattVolt\") FROM \"LoRaware_1\" ",
     "select": [
      [
       { "params": [ "HR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "O2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_2",
     "query": "SELECT LAST(\"BattVolt\") FROM \"LoRaware_2\" ",
     "select": [
      [
       { "params": [ "HR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"BattVolt\") FROM \"LoRaware_3\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_4",
     "query": "SELECT LAST(\"BattVolt\") FROM \"LoRaware_4\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_1",
     "query": "SELECT last(\"BattVolt\") FROM \"LoRaware_1\"",
     "select": [
      [
       { "params": [ "BattVolt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_2",
     "select": [
      [
       { "params": [ "BattVolt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_3",
     "select": [
      [
       { "params": [ "BattVolt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_4",
     "select": [
      [
       { "params": [ "BattVolt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LoRaware 1 - Battery Capacity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 16 },
   "format": "percent",
   "targets": [
    {
     "measurement": "LoRaware_1",
     "query": "SELECT last(\"BattPercent\") FROM \"LoRaware_1\"",
     "select": [
      [
       { "params": [ "BattPercent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LoRaware 2 - Battery Capacity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 16 },
   "format": "percent",
   "targets": [
    {
     "measurement": "LoRaware_1",
     "query": "SELECT last(\"BattPercent\") FROM \"LoRaware_2\"",
     "select": [
      [
       { "params": [ "BattPercent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LoRaware 3 - Battery Capacity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 16 },
   "format": "percent",
   "targets": [
    {
     "measurement": "LoRaware_1",
     "query": "SELECT last(\"BattPercent\") FROM \"LoRaware_3\"",
     "select": [
      [
       { "params": [ "BattPercent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LoRaware 4 - Battery Capacity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 16 },
   "format": "percent",
   "targets": [
    {
     "measurement": "LoRaware_1",
     "query": "SELECT last(\"BattPercent\") FROM \"LoRaware_4\"",
     "select": [
      [
       { "params": [ "BattPercent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signal-to-Noise Ratio",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "LoRaware 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_1",
     "select": [
      [
       { "params": [ "SNR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_2",
     "select": [
      [
       { "params": [ "SNR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_3",
     "select": [
      [
       { "params": [ "SNR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_4",
     "select": [
      [
       { "params": [ "SNR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "LoRaware 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_1",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_2",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_3",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LoRaware 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LoRaware_4",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}